
project_id = "pizlzaomylxreizohewd"

[functions.generate-daily-matches]
verify_jwt = false

[functions.ai-profile-analysis]
verify_jwt = false

[functions.ai-enhanced-matching]
verify_jwt = false

[functions.copilot-chat]
verify_jwt = false

[functions.spotify-integration]
verify_jwt = true
