// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pizlzaomylxreizohewd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpemx6YW9teWx4cmVpem9oZXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDQyOTUsImV4cCI6MjA2NjA4MDI5NX0.KsD1rrVyRQxM0rckta5p_50xahz_ju4XiPw-LCaTnpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);